### ISSUE TITLE
Add starters for fabric8/camel etc spring-boot-starters

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-forge#233]
to the forge spring-boot project-new command so we have ours included as well.

**Comment by jstrachan** [comment]
examples off the top of my head:
- https://github.com/fabric8io/spring-cloud-kubernetes for spring-cloud-kubernetes + zipkin + netflix
- https://github.com/fabric8io/kubeflix
- CXF - though not sure the starter is ready https://issues.apache.org/jira/browse/CXF-6834 https://github.com/spring-projects/spring-boot/pull/5659
