### ISSUE TITLE
to add a new endpoint to a route; you can't add an Endpoint to the `from`

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-forge#293]
and if you add the endpoint clicking on the Route, it adds it before the from which is odd; should add it afterwards I'd have thought?

**Comment by davsclaus** [comment]
Its the add-endpoint-xml command that need a bit of love.

There is a add-endpoint command for IDEA/Eclipse users that adds at the cursor position.

**Comment by davsclaus** [comment]
Yeah either it should add it straight after `<from>` or it should add it to the end of the route ?

**Comment by jstrachan** [comment]
yeah, I figure if you click on a node and select `Add` it should add after it or inside it if it accepts children. 

for these kinds of node we add after it (so its the next sibling in the selected node's children collection):
- from, choice, to, transform etc

for these kinds of nodes we add as the last child inside it (so its the last child of the selected node)
- when, otherwise, filter, route
