### ISSUE TITLE
[Camel]"Project Add DataFormat" silently fails and report success

### ISSUE THREAD

**Issue by apupier** [fabric8io/fabric8-forge#359]
- in JBDS, install Forge Camel addon
- create a Fuse Camel project (you can install Fuse Tooling for that)
- Open the xml (or java) file corresponding to the Camel Route
- Ctrl+4
- Choose "Camel: Project Add DataFormat"
- Select a data format (avro for instance
- wait a long time that the operation finish (in case it is the first use)

--> a notification pops up to say that it works well

--> nothing has been added in the file

--> only a dependency in pom.xml has been added

**Comment by davsclaus** [comment]
What version of the camel addon and jboss forge are you using?

**Comment by apupier** [comment]
2.0.100 for JBoss Forge UI plugin
2-2-210 for Camel addon
3.3.2.Final for the Forge

**Comment by davsclaus** [comment]
Add data format / component / language is only for adding the dependency in the pom.xml - nothing else.

**Comment by apupier** [comment]
I don't really see the added-value then and naming is ambiguous. i was expecting a dataformat added as a global configuration or directly at the cursor point.
Do you have some use cases?
I would suggest to remove this command or to find a more specific name ("Add DataFormat dependency" maybe?).

**Comment by davsclaus** [comment]
These commands do as they say in their description, and they have project in they command name

**Comment by davsclaus** [comment]
And they are needed in some cases like the iPaaS. And they can be good for Eclipse too as it has an wizard where you can filter. Especially for components where we have 180+, so filtering for eg HTTP to find http capable components.
