### ISSUE TITLE
[Camel]Empty target package is not supported for creating a new Camel component

### ISSUE THREAD

**Issue by apupier** [fabric8io/fabric8-forge#361]
- in JBDS, install Forge Camel addon
- create a Fuse Camel project (you can install Fuse Tooling for that)
- Open the xml or java file corresponding to the Camel Route
- Ctrl+4
- Choose:  "Camel: new Component"
- fill the wizard
- keep empty or remove content of "Target Package" field

--> when clicking Finish, there is an error

2 solutions:
- don't allow empty target package
- support to create in (default package)

**Comment by davsclaus** [comment]
What version of the camel addon and jboss forge are you using?

**Comment by apupier** [comment]
2.0.100 for JBoss Forge UI plugin
2-2-210 for Camel addon
3.3.2.Final for the Forge

**Comment by davsclaus** [comment]
Yes lets make the package name required field.

**Comment by davsclaus** [comment]
If you can build from source you are welcome to test this latest fix if it helps you.

**Comment by davsclaus** [comment]
There is a new 2.2.212 release out now
