### ISSUE TITLE
[Camel] Cannot add endpoint in Java file

### ISSUE THREAD

**Issue by apupier** [fabric8io/fabric8-forge#363]
- in JBDS, install Forge Camel addon
- create a Fuse Camel project with Java DSL(you can install Fuse Tooling for that)
- Open the java file corresponding to the Camel Route
- Ctrl+4
- Choose: "Camel; Add endpoint"
- fill wizard
- click finish

a notification error pops up:
![image](https://cloud.githubusercontent.com/assets/1105127/16580657/c076452c-42a5-11e6-8b45-943d39fec8ac.png)

I'm on Windows

**Comment by davsclaus** [comment]
Yeah I fixed that recently, should be there in the next release.

**Comment by davsclaus** [comment]
Reported and fixed by ticket: https://github.com/fabric8io/fabric8-forge/issues/353

**Comment by apupier** [comment]
nice that it is already fixed
