### ISSUE TITLE
[Camel] List of Component to add is based on latest camel version, not the project version

### ISSUE THREAD

**Issue by apupier** [fabric8io/fabric8-forge#364]
so it means that we can add a component which is not available with the project version, it ends with "Missing artifact error"
- in JBDS, install Forge Camel addon
- create a Fuse Camel project (you can install Fuse Tooling for that) based on camel 2.15.1-redhat-620133
- Open the xml or java file corresponding to the Camel Route
- Ctrl+4
- Choose:  "Camel: new Component"
- Choose camel-braintree
- fill wizard
- click finish

--> the added artefact is nto availabel in this version

![image](https://cloud.githubusercontent.com/assets/1105127/16581091/f881edc0-42a7-11e6-9aa0-a822dc963987.png)

**Comment by davsclaus** [comment]
Yes its the version shipped with the forge-camel addon.

With Apache Camel 2.18 onwards the catalog will support switching versions if access to the internet.
https://github.com/fabric8io/fabric8-forge/issues/336

**Comment by davsclaus** [comment]
And for JBoss Fuse product you guys need to build forge-camel with your version of camel so its using that version out of the box. And also for switching to new version over the internet, may require you to add that custom maven repo for jboss fuse releases so the camel-catalog can find and download those redhat release.

**Comment by apupier** [comment]
I don't get it.
Why the version added in pom is not the one shipped in forge-camel addon? or the catalog is nto matching the version in the forge-camel addon?

**Comment by davsclaus** [comment]
You do not want to use mixed Camel versions, so it uses the same version as camel-core.

What is needed is the camel addon to use that same version in the catalog, so the list of components are only what you can use for this particular Camel version.
