### ISSUE TITLE
[Camel]"Add endpoint" is nto working on the Fuse Tooling Camel editor on Source tab

### ISSUE THREAD

**Issue by apupier** [fabric8io/fabric8-forge#365]
- in JBDS, install Forge Camel addon
- create a Fuse Camel project (you can install Fuse Tooling for that)
- open it using the Fuse Camel editor
- go to source tab
- Ctrl+4
- Choose:  "Camel: Add endpoint"
- fill wizard
- click finish

--> I had various errors, depednening on previous steps but shoudl be all related to Fuse Tooling editor integration:
- put the value in the previously selected editor on whcih I added an endpoint (xml one)
- notification popup with resource exception on pom.xml

**Comment by davsclaus** [comment]
Yeah should work better in next release.

You can build from source and run with SNAPSHOT if you want, eg install 2.3-SNAPSHOT. Or if you have patience you can use the forge install from github, and point it to this github repo.

**Comment by davsclaus** [comment]
But what I do is to build the camel forge-addon at
https://github.com/fabric8io/fabric8-forge/tree/master/addons/camel

And then from forge in IDEA use the install addon, and type in the text

```
io.fabric8.forge:camel,2.3-SNAPSHOT
```

To install to latest code.

**Comment by davsclaus** [comment]
There is a new 2.2.212 release out now
