### ISSUE TITLE
fabric8-forge - Has 2x REST services

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-forge#369]
We see this in the logs

Both io.fabric8.forge.rest.RootResource#ping and io.fabric8.forge.rest.RootResource#ping are equal candidates for handling the current request which can lead to unpredictable results

**Comment by davsclaus** [comment]
Ah darn CDI and JAX-RS and CXF. So both some kind of class canning finds the JAX-RS resource classes and auto adds to CXF, and then also CDI because of @Inject stuff.

**Comment by jstrachan** [comment]
aha! The main reason for CDI was Forge; wonder if moving to RestEasy is easier?

**Comment by davsclaus** [comment]
Yeah have been looking inside the CXF RS code and its scary bunch of code. 
Its actually hard to figure out how to tell it which "magic" to turn on/off. And CDI isn't its strong side.

**Comment by jstrachan** [comment]
we could also experiment one day with using WF Swarm too? I mean we just want JAXRS + CDI in a WAR really which sounds like WF Swarm's kinda sweet spot.

**Comment by davsclaus** [comment]
Yeah I am trying WF-Swam. That could be a good idea to use as microservice container for CDI. I got the ping service running without any fuzz.

**Comment by davsclaus** [comment]
Though we may need the REST Cors filter and then I wonder how to hook that into WF-Swarm

**Comment by davsclaus** [comment]
Ah found it and added that code and we got the filter also
https://github.com/wildfly-swarm/wildfly-swarm-examples/blob/master/jaxrs/swagger/src/main/java/org/wildfly/swarm/examples/jaxrs/swagger/CORSFilter.java

**Comment by jstrachan** [comment]
yay!! - was just gonna say I made sure that used standard servlet filters anyways

**Comment by davsclaus** [comment]
Ah darn, some CXF library is in there somewhere due to fabric8-git that uses CXF as client and then WF-Swarm and CDI somehow barfs

Caused by: org.jboss.weld.exceptions.DefinitionException: WELD-000071: Managed bean with a parameterized bean class must be @Dependent: class org.apache.cxf.jaxrs.provider.XSLTJaxbProvider"}}

**Comment by jstrachan** [comment]
ah - the rest-utils has CXF stuff in there. Just copy/paste the RestCorsFilter class and you can exclude that dependency.

**Comment by jstrachan** [comment]
I created a gitrepo-resteasy to avoid the gitrepo-api being dependent on CXF; looks like it'd be good to get that back so you can try it in forge?

**Comment by jstrachan** [comment]
wanna try revert this commit (you deleted it ;) https://github.com/fabric8io/fabric8/pull/4963/commits/dcf7e2cbacae230e2583b4a841c469afb65354fa
and see if a local build of that and using gitrepo-resteasy instead of gitrepo-api helps?

**Comment by davsclaus** [comment]
Yeah thanks - CXF is a ****\* so they added CDI beans directly in their rs-frontend JAR so you cannot use CXF without it goes nuts about CDI compliant crap. And using the beans.xml you cannot even get WF-Swarm to ignore scanning it, I even added a text with F**\* Y*\* in the xml so the xml parser should fail, but its not triggered.

**Comment by jstrachan** [comment]
yeah - WF Swarm comes with  RESTEasy OOTB right; so we probably wanna ditch all CXF dependenices from Forge

**Comment by davsclaus** [comment]
Yeah can try the resteasy-git stuff. I couldn't get WF-Swarm to work this current code as it complains about that CXF scanning error and I cannot disabled it, and weld/swarm dont give precise error where/what is causing this - too much magic goes on.

**Comment by jstrachan** [comment]
yeah - we should be able to remove all cxf dependences pretty easily

**Comment by davsclaus** [comment]
Okay got gitrepo-resteasy to be used instead of CXF and in wf-swarm I can get the _ping to work. The trouble is furnace with forge as it fails to be created with all kind of classloading errors. So I cannot execute the forge commands.

**Comment by jstrachan** [comment]
damn!!! Sorry about that!

OK maybe we could try jetty with resteasy?

**Comment by davsclaus** [comment]
Yeah I am trying resteasy now. But our git-client uses CXF RS client. We may need to migrate that to resteasy also so its the same.

Also instead of using Jetty we could use undertow which is more lightweight and performant.

**Comment by RobinsChens** [comment]
so have you fixed this problem,please tell me how to solve it

**Comment by davsclaus** [comment]
Its fixed in CXF 3.1.9 which has not been released

**Comment by davsclaus** [comment]
Should be fixed when we upgrade CXF
https://github.com/fabric8io/fabric8-forge/issues/772

**Comment by davsclaus** [comment]
CXF upgraded
