### ISSUE TITLE
fabric8-setup - Use the new f-m-p plugin

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-forge#400]
to integrate with docker/f8 instead of the older f8/dmp plugins.
Look at the new quickstarts how to do this.

**Comment by davsclaus** [comment]
Look at this qs for what to change
https://github.com/fabric8-quickstarts/spring-boot-camel/blob/master/pom.xml

**Comment by davsclaus** [comment]
@rawlingsj this ticket is about the forge to use the new f8 plugin

**Comment by jstrachan** [comment]
I've just PR'd a partial fix so at least it adds the correct maven plugin now. More work is required to properly deal with base images (though I guess f-m-p could do that bit too!). We probably generate some redundant properties too which we could tidy up
