### ISSUE TITLE
Problems creating project from quickstart walk through HTTP 500 error 

### ISSUE THREAD

**Issue by sbadakhc** [fabric8io/fabric8-forge#429]
I'm using fabric8 via the vagrant virtual machine and attempting to create a devops circuit via the fabric8 forge wizard.  See screen capure
![screenshot from 2016-08-01 15-43-35](https://cloud.githubusercontent.com/assets/2914400/17295929/feb726ee-57fe-11e6-8435-72c122b7efb4.png)

**Comment by davsclaus** [comment]
Do you have any steps to re-produce this?

**Comment by sbadakhc** [comment]
I cannot reproduce it anymore...looks like a transient error...closing!
