### ISSUE TITLE
fails to create Integration test 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-forge#430]
I got this when trying to create an integration test via the fabric8-console:

```
Caused by: org.jboss.forge.addon.facets.FacetNotFoundException: No Facet of type [interface org.jboss.forge.addon.parser.java.facets.JavaSourceFacet] is installed.
```

**Comment by davsclaus** [comment]
What project do you generate? Is it "integration project" or some other kind ?

**Comment by jstrachan** [comment]
tried it in a few - integration project, microservice

**Comment by davsclaus** [comment]
Trying to fix this now.

Spotted this warning also

WARNING: Could not find the version for groupId: io.fabric8 artifactId: fabric8-arquillian in: {org.apache.maven.wagon/wagon-webdav-jackrabbit=2.10, org.jboss.shrinkwrap.resolver/shrinkwrap-resolver-impl-maven=2.2.1, org.jboss.arquillian.junit/arquillian-junit-container=1.1.11.Final, io.fabric8/fabric8-maven-plugin=3.1.7, org.apache.maven.plugins/maven-failsafe-plugin=2.19, junit/junit=4.12, io.fabric8/arquillian-fabric8=2.3-SNAPSHOT, org.apache.maven.plugins/maven-javadoc-plugin=2.10.3, io.fabric8.archetypes/archetypes-catalog=2.2.161, io.hawt/hawtio-maven-plugin=1.4.65, io.fabric8/kubernetes-api=2.2.145, org.jolokia/docker-maven-plugin=0.15.11, org.apache.maven.plugins/maven-surefire-plugin=2.17}

**Comment by davsclaus** [comment]
A PR to fix this is merged: https://github.com/fabric8io/fabric8-forge/pull/436

**Comment by davsclaus** [comment]
Using the released version of fabric8-forge on minishift I create "integration" and use the big CI/CD pipeline and from the CI build log I see integration tests being run, it takes 1m30s

```

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18.1:verify (default-cli) @ myiapp ---
[INFO] Failsafe report directory: /home/jenkins/workspace/workspace/myiapp/target/failsafe-reports
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:32 min
[INFO] Finished at: 2016-08-04T11:18:57+00:00
[INFO] Final Memory: 20M/60M
[INFO] ------------------------------------------------------------------------
```
