### ISSUE TITLE
make it easier to enter dependencies in a one-liner

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8-forge#483]
we have to type out the full dependency title when we try to: `project-new --type spring-boot --dependencies "Core: Web"` 

would be nicer if we could just do "core-web", "core-whatever", or "ops-foo" etc.

per @gastaldi we can use:

> @gastaldi   UIInput.setItemLabelConverter(Commands::shellifyOptionNameDashed)
> @gastaldi   just that, if context.getProvider().isGUI() returns false

**Comment by davsclaus** [comment]
Thanks this is better. I think I will remove the group name as that just repeat must stuff eg, web-web etc.

Also found a little Forge bug: https://issues.jboss.org/browse/FORGE-2690

**Comment by davsclaus** [comment]
You can now use shorter names

```
[deleteme]$ spring-boot-new-project --dependencies web actuator apache-camel
```
