### ISSUE TITLE
WildFly Swarm dependencies in web console should use shorter labels

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-forge#514]
See this video
https://www.youtube.com/watch?v=hXZmlEbwWkY

And when @christian-posta adds the WF dependencies then their labels are big. We should do like SB where its just JPA, Undertow etc.

![screen shot 2016-09-09 at 5 16 15 pm](https://cloud.githubusercontent.com/assets/477100/18392228/4cfb9df0-76b1-11e6-992e-e9313d15614c.png)

**Comment by davsclaus** [comment]
This is from the wildfly-swarm addon, and not in fabric8-forge, so it need to be fixed on that side

**Comment by gastaldi** [comment]
Fixed, can you please give it a try by reinstalling the addon? I can release a new Maven version if that's ok.

**Comment by davsclaus** [comment]
Sorry @gastaldi dont have the time. Just put it our in the regular release schedule and we will pick it up and report bak.

**Comment by gastaldi** [comment]
No worries I already testes and released ;)

**Comment by davsclaus** [comment]
Should be fixed in new forge release
