### ISSUE TITLE
camel-new-component command leads to ClassCastException if package-info.java is present

### ISSUE THREAD

**Issue by jamesnetherton** [fabric8io/fabric8-forge#526]
[This](https://github.com/fabric8io/fabric8-forge/blob/master/addons/utils/src/main/java/io/fabric8/forge/addon/utils/completer/PackageNameCompleter.java#L45) line in `PackageNameCompleter` seems to be problematic if you try to use `camel-new-component` and there's a package-info.java present somewhere in the project.

In this case the type returned is `JavaPackageInfoImpl`, hence you get:

```
org.jboss.forge.roaster.model.impl.JavaPackageInfoImpl cannot be cast to org.jboss.forge.roaster.model.JavaClass
```

**Comment by davsclaus** [comment]
Thanks for reporting
