### ISSUE TITLE
pick a pipeline for a new project in the UI take long time

### ISSUE THREAD

**Issue by abouchama** [fabric8io/fabric8-forge#601]
JBoss forge download from internet on new projects while we figure out what plugins we could use - usually the first time you try it its slow; after that its much better when its warmed its cache

it'd be nice to try optimise it a bit - maybe pre-loading them for all projects and caching them

**Comment by davsclaus** [comment]
Yeah however its forge-core and its project-new command that is doing this, so it would be something maybe we need to ask @gastaldi from forge team if there is a way to warmup project-new command during startup.

**Comment by gastaldi** [comment]
Right now Forge builds the whole project to have access to model information (it uses Maven ProjectBuilder and Plexus to configure it, which is a bit heavyweight). I'm working on optimizing that to use the Maven Model Builder instead. See https://issues.jboss.org/browse/FORGE-2699 for more details

**Comment by gastaldi** [comment]
Not sure if it's directly related to this issue, but I believe it should give a performance boost

**Comment by gastaldi** [comment]
@abouchama and @davsclaus can you provide more details on how to reproduce that?

**Comment by davsclaus** [comment]
@gastaldi oh I have just seen in the logs from fabric8-forge that it downlods the archetype from project-new after you have chosen one.

So we have custom project types that are a maven archetype such as
https://github.com/fabric8io/fabric8-forge/blob/master/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/projecttypes/CamelProjectType.java

With a step
https://github.com/fabric8io/fabric8-forge/blob/master/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/projecttypes/CamelProjectArchetypeStep.java

... from forge
https://github.com/fabric8io/fabric8-forge/blob/master/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/archetype/Fabric8ArchetypeCatalogStep.java

So I guess down there somewhere forge is downloading the archetype. Well that is of course needed. Not sure if there is a way to make it pre download them.

We do have two set of custom maven catalogs we add to forge, which contain all our custom maven archetypes the users can select when he/she creates a new project. So its all of those we would like to pre-download.
https://github.com/fabric8io/fabric8-forge/tree/master/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/archetype

We have this initializer class that preload forge and setup some stuff
https://github.com/fabric8io/fabric8-forge/blob/master/fabric8-forge-core/src/main/java/io/fabric8/forge/rest/main/ForgeInitialiser.java

... maybe it can be enhanced to do something for project-new about downloading those maven archetypes.

**Comment by davsclaus** [comment]
I guess to reproduce you would need either to run fabric8 on kubernetes, or maybe simpler is just to run forge offline and then install the camel addon (which contains those project-new archetypes).

http://fabric8.io/guide/forge.html

The latest version of fabric8-forge camel commands is
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.fabric8.forge%22%20AND%20a%3A%22camel%22

is 2.3.73 but you can see above in maven central if there is a newer.

**Comment by davsclaus** [comment]
From the logs where it downloads an archetype
```
Nov 22, 2016 11:05:50 AM org.jboss.forge.furnace.manager.maven.JULMavenTransferListener transferInitiated
INFO: Downloading: http://repo1.maven.org/maven2/io/fabric8/archetypes/spring-boot-camel-xml-archetype/2.2.185/spring-boot-camel-xml-archetype-2.2.185.jar
Nov 22, 2016 11:05:51 AM org.jboss.forge.furnace.manager.maven.JULMavenTransferListener transferProgressed
INFO: 4/12 KB
Nov 22, 2016 11:05:51 AM org.jboss.forge.furnace.manager.maven.JULMavenTransferListener transferProgressed
INFO: 8/12 KB
Nov 22, 2016 11:05:51 AM org.jboss.forge.furnace.manager.maven.JULMavenTransferListener transferProgressed
INFO: 12/12 KB
Nov 22, 2016 11:05:51 AM org.jboss.forge.furnace.manager.maven.JULMavenTransferListener transferProgressed
INFO: 12/12 KB
Nov 22, 2016 11:05:51 AM org.jboss.forge.furnace.manager.maven.JULMavenTransferListener transferCompleted
INFO:
Nov 22, 2016 11:05:51 AM org.jboss.forge.furnace.manager.maven.JULMavenTransferListener transferSucceeded
INFO: Downloaded: http://repo1.maven.org/maven2/io/fabric8/archetypes/spring-boot-camel-xml-archetype/2.2.185/spring-boot-camel-xml-archetype-2.2.185.jar (12 KB at 17.5 KB/sec)
Creating archetype using Maven groupId: org.example, artifactId: mycamel7, version: 1.0.0-SNAPSHOT in directory: /tmp/fabric8-forge/user/gogsadmin/mycamel7
Using replace properties: {spring-boot-version=1.4.1.RELEASE}
```

**Comment by gastaldi** [comment]
I think it would help if you made FabricArchetypeCatalogFactory @ApplicationScoped?

**Comment by gastaldi** [comment]
One solution would be to read all the archetypes entries in the registered archetype catalogs and resolving them using the DependencyResolver. That would download the archetypes and make them available in the local repository.

**Comment by davsclaus** [comment]
Ah thanks. Wonder if there is a way to query forge for all the archetype catalogs?

Is there a way with CDI injection etc to inject all the instances of `ArchetypeCatalogFactory` ? As we have more than one factory, one for camel, and another for fabric8.

**Comment by davsclaus** [comment]
We have this app that starts up fabric8-forge
https://github.com/fabric8io/fabric8-forge/blob/master/fabric8-forge-core/src/main/java/io/fabric8/forge/rest/main/ForgeRestApplication.java

And it has that forge initailizer that preloads the commands. But would be good to add that logic to resolve all those maven archetypes from those catalogs.
https://github.com/fabric8io/fabric8-forge/blob/master/fabric8-forge-core/src/main/java/io/fabric8/forge/rest/main/ForgeInitialiser.java

Sorry its not the pretties code on the internet ;)

**Comment by gastaldi** [comment]
The best way to achieve that would be to 
`@Inject ArchetypeCatalogFactoryRegistry registry ;`
and call `registry.getArchetypeCatalogFactories()` to iterate through each available `ArchetypeCatalogFactory`

**Comment by gastaldi** [comment]
You would need to grab it from the `AddonRegistry` (using `Furnace.getAddonRegistry().getServices(ArchetypeCatalogFactoryRegistry.class).get()`) to be able to @Inject in your code, similar to what is done in https://github.com/fabric8io/fabric8-forge/blob/master/fabric8-forge-core/src/main/java/io/fabric8/forge/rest/producer/FurnaceProducer.java

**Comment by davsclaus** [comment]
Thanks @gastaldi I got this working to download the archetype itself. Now I need to expand on that and download the JARs the archetypes uses.

**Comment by davsclaus** [comment]
It maybe be better at build time to let maven create all those projects from the archetype catalogs and then .zip the .m2/repository into the docker image.

Then they are already downloaded when the container start up and is not slow to download a bunch of JARs when starting up.

**Comment by davsclaus** [comment]
Its a bit faster now, but there is some room to optimize on the backend side as forge initializes the steps and commands several time, and the re-init costs additional overhead.

Also there is some git commands that does some stuff which I haven't looked to optimize yet.

**Comment by davsclaus** [comment]
Its faster now. So lets open a new ticket if people find the newer to be too slow also.

**Comment by abouchama** [comment]
I just made a test with the latest version: **fabric8/fabric8-forge:2.3.86** and it's faster than before.

Thanks.
