### ISSUE TITLE
Logging and Metrics Templates Gone Missing (Prometheus/Grafana/ES/Kibana)

### ISSUE THREAD

**Issue by yongk802** [fabric8io/fabric8-forge#621]
The documentation in the guide talks about setting up logging using elasticsearch/kibana and metrics using prometheus/grafana. 

http://fabric8.io/guide/logging.html
http://fabric8.io/guide/metrics.html

These templates used to be included in the distro, but it looks like they've been taken out starting in 2.3.53.

https://repo1.maven.org/maven2/io/fabric8/forge/distro/distro/2.3.53/

We were wondering where these templates have gone. Is there a new recommendation for logging/metrics that needs to be documented? In the meantime, we are manually pulling in the templates from 2.3.52.

Thanks!

**Comment by davsclaus** [comment]
Please log this against fabric8
https://github.com/fabric8io/fabric8

And I think there may be some tickets about this
