### ISSUE TITLE
improve startup time?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-forge#654]
the first java project created tends to be quite slow as fabric8-forge downloads from maven central all kinds of dependencies.

would be nice to pre-cache those more on startup

**Comment by davsclaus** [comment]
When you create a new project then the archetype is downloaded from maven over the internet. I guess its populated in some local m2/repository.

So we could maybe find a way to download all of those on startup.

**Comment by davsclaus** [comment]
See also #704 where we have some optimizations in the works

**Comment by davsclaus** [comment]
There is some tests that create new projects and therefore download the JARs to a local repo. We could make this more formalized for the release profile and move it to some maven plugin that downloads those.

But the size of the repo is a big big its about 400mb. So our fabric8-forge docker image will be increased by this size. However then creating those projects using the wizard should be much faster as no download is needed anymore.

**Comment by davsclaus** [comment]
We could maybe omit the vanilla Apache Camel archetypes as people are likely to create the fabric8 quickstart based examples instead.

**Comment by davsclaus** [comment]
Also for local development we could maybe hostPath the localMavenRepo into the docker-image at k8s if running local. As building the docker image with the 444mb maven repo embedded is slow - takes 6+ minutes on my laptop.

**Comment by davsclaus** [comment]
With the m2 repo embedded I get a forge startup error now
```
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.jboss.forge.addon.configuration.ConfigurationFactoryImpl.getUserConfiguration(ConfigurationFactoryImpl.java:76)
	... 59 more
```

**Comment by davsclaus** [comment]
I think its .forge missing with a config.properties file that it attempt to auto create but cannot do for some odd reason. Lets try to embed this forge OOTB

**Comment by davsclaus** [comment]
A bit better error message
https://issues.jboss.org/browse/FORGE-2704

Now I embed an empty .forge/config.properties file and it seems to move on

**Comment by davsclaus** [comment]
However we have an issue with this file
https://github.com/davsclaus/fabric8-forge/blob/014fd941b9e5ecfbb2677403c1ad30ee35f2c317/fabric8-forge/src/main/docker/m2/settings.xml

Then it can be out of sync with the local m2 repo and I got some error about file not found

**Comment by davsclaus** [comment]
Okay so our CI pipeline then starts jobs and then download the internet again because nexus dont include the JARs.

Its maybe better to build a maven plugin that we can add to the nexus docker image, that can include the JARs OOTB, and then get fabric-forge to use the nexus repo which it does using that settings.xml file.

**Comment by davsclaus** [comment]
So got the maven plugin working and it downloads those JARs from the fabric8 archetype catalog.

Because its slow, we could maybe put it in the release profile by default, so the release will have the JARs embedded.

And then for developers it can be optional, and ppl can run it with

    mvn compile fabric8-forge:download

And then keep the localMavenRepo directory so its only build once.

**Comment by davsclaus** [comment]
This PR will improve startup time
https://github.com/fabric8io/fabric8-forge/pull/740

**Comment by davsclaus** [comment]
The fabric8-forge image now contains the pre downloaded JARs and also configured to use the nexus as maven repository so any extra downloads will use nexus instead of maven central directly.
