### ISSUE TITLE
ipaas-search-connectors seems to cache results

### ISSUE THREAD

**Issue by gashcrumb** [fabric8io/fabric8-forge#690]
Could be maven causing this.  But basically:

1)  Call ipaas-search-connectors
2)  upload a new connector jar to nexus
3)  Call ipaas-search-connectors again

only the connectors you got back for step 1 are returned.  I can only get my newly uploaded connector to show up if I kill the fabric8-forge pod and let it get restarted.

**Comment by davsclaus** [comment]
There is a background thread the re-index the nexus repo and runs every 60 second.
https://github.com/fabric8io/django/blob/master/addons/ipaas/src/main/java/io/fabric8/forge/ipaas/repository/NexusConnectionRepository.java#L52

**Comment by davsclaus** [comment]
Yeah let me see if forge don't detect that CDI bean and starts it (CDI is lovely)

**Comment by davsclaus** [comment]
So you need to run one of the django commands first to have that background thread start up. I guess forge dont scan CDI beans or something. Will try with some EjbStartup annotations

**Comment by davsclaus** [comment]
Okay the new forge release starts the indexer on startup.

You need to name the artifactId of the connector with `-connector` as suffix. The wizard do not enforce that as its a wizard OOTB from jboss forge (project-new) which we cannot control.
