### ISSUE TITLE
Jenkinsfile for non container build

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-forge#712]
We need a plain Jenkinsfile for projects that are not docker/container/kubernetes based. For example Camel connectors for iPaaS.

When creating a Camel connector we can include the Jenkinsfile in that source code, so its not in those default chooseable pipelines you see in the fabric8 web console.

@rawlingsj wonder if you can help me or point me to a plain jenkinsfile for a plain maven project. All it need to do is to install the JAR to the local nexus repo.

**Comment by davsclaus** [comment]
@gashcrumb so when we get this sorted you should be able to create new connectors from the fabric8 web console.

**Comment by gashcrumb** [comment]
ah awesome that'll definitely be handy!

**Comment by davsclaus** [comment]
Ah there is the Deploy pipeline OOTB we can use.

**Comment by davsclaus** [comment]
Just need the create-connector wizard to default select that and omit the others so there is no choices for the end user.

**Comment by davsclaus** [comment]
@gashcrumb okay so you can build your own connectors and the search command should see the new ones, when it runs its index again (every 60th sec).

A few steps to ensure (until we improve fabric8-forge)

- name the artifactId of the project with `-connector` as prefix, eg `awesome-connector`
- use the Deploy as the pipeline (not any of the others)

**Comment by davsclaus** [comment]
And the indexer should log if it finds any connectors in the fabric8-forge logs such as
```
Indexing Nexus http://nexus/service/local/data_index +++ start +++
Found connector: org.example:cake-connector:1.0.0-SNAPSHOT
Indexing Nexus http://nexus/service/local/data_index +++ end +++
```

**Comment by davsclaus** [comment]
And you can run the index yourself from the nexus url

   http://192.168.64.20:31168/service/local/data_index?q=connector

eg run gofabric8 service nexus to get the ip:port and then that url above is what fabric8-forge command uses

**Comment by davsclaus** [comment]
Duplicate of #713
