### ISSUE TITLE
Add REST API to obtain a list of all Component Labels.

### ISSUE THREAD

**Issue by KurtStam** [fabric8io/fabric8-forge#762]
This is needed for the ipaas UI. 

It would call:
https://github.com/apache/camel/blob/master/platforms/catalog/src/main/java/org/apache/camel/catalog/CamelCatalog.java#L233

and return a list of strings containing all labels.

**Comment by davsclaus** [comment]
See
https://issues.apache.org/jira/browse/CAMEL-10561

Will add this to Apache Camel and then we can in the interim time copy that to fabric8 until we upgrade to Camel 2.19.0.

**Comment by davsclaus** [comment]
I made a little standalone app you can try also which has embedded swagger ui

![screen shot 2016-12-06 at 1 55 47 pm](https://cloud.githubusercontent.com/assets/477100/20926276/c3c23c88-bbbb-11e6-8c05-293cafe77aa2.png)

**Comment by davsclaus** [comment]
Implemented this on the Apache Camel side, now need to port that to django so we can have it included for ipaas.

**Comment by davsclaus** [comment]
There is a new django release which has camel-catalog-rest included. So I need to hook this up into fabric8-forge-core to hook that up as a JAX-RS app.

**Comment by davsclaus** [comment]
The camel catalog REST api is now baked into fabric8-forge

However the swagger json doc is not included as this requires CXF 3.1.7 or newer. And we are stuck on 3.1.6 due fabric8 has some fabric8-cxf components that are using this version and they haven't been upgraded. Not sure if that is easy.

![screen shot 2016-12-06 at 6 05 40 pm](https://cloud.githubusercontent.com/assets/477100/20935375/bf90c008-bbde-11e6-97eb-81e82da851cc.png)

**Comment by davsclaus** [comment]
To find all Camel components, this API returns their names

camel-catalog/findComponentNames

**Comment by davsclaus** [comment]
You can see the API here
https://github.com/fabric8io/django/blob/master/camel-catalog-rest/src/main/java/org/apache/camel/catalog/rest/CamelCatalogRest.java#L35

**Comment by davsclaus** [comment]
Logged a ticket to upgrade CXF
https://github.com/fabric8io/fabric8/issues/6622

**Comment by davsclaus** [comment]
See #767
